=== Carloski9/IronBase-Track/docs/xml/esquema_ejercicios.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="catalogo_ejercicios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ejercicio" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3"/>
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="grupo_muscular" type="xs:string"/>
                            <xs:element name="subgrupo_muscular" type="xs:string"/>
                            
                            <xs:element name="tipo_mecanica">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Multiarticular"/>
                                        <xs:enumeration value="Monoarticular"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="lateralidad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Bilateral"/>
                                        <xs:enumeration value="Unilateral"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="material">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Libre_Barra"/>
                                        <xs:enumeration value="Libre_Mancuernas"/>
                                        <xs:enumeration value="Polea"/>
                                        <xs:enumeration value="Maquina_Discos"/>
                                        <xs:enumeration value="Maquina_Placas"/>
                                        <xs:enumeration value="Peso_Corporal"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Carloski9/IronBase-Track/docs/xml/ejercicios.xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo_ejercicios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquema_ejercicios.xsd">
    
    <ejercicio id="1">
        <nombre>Sentadilla con Barra</nombre>
        <grupo_muscular>Piernas</grupo_muscular>
        <subgrupo_muscular>Cuadriceps</subgrupo_muscular>
        <tipo_mecanica>Multiarticular</tipo_mecanica>
        <lateralidad>Bilateral</lateralidad>
        <material>Libre_Barra</material>
    </ejercicio>

    <ejercicio id="13">
        <nombre>Press Banca Mancuernas</nombre>
        <grupo_muscular>Pectoral</grupo_muscular>
        <subgrupo_muscular>Haz Esternocostal</subgrupo_muscular>
        <tipo_mecanica>Multiarticular</tipo_mecanica>
        <lateralidad>Unilateral</lateralidad>
        <material>Libre_Mancuernas</material>
    </ejercicio>

</catalogo_ejercicios>
